
# 吴恩达Coursera深度学习课程 DeepLearning.ai 编程作业（1-2）

 **原作者：Koala_Tree** [吴恩达Coursera深度学习课程 DeepLearning.ai 编程作业（1-2）](http://blog.csdn.net/koala_tree/article/details/78057033 )
 
## Part 1：Python Basics with Numpy (optional assignment)

### 1 - Building basic functions with numpy

Numpy is the main package for scientific computing in Python.(Numpy 是在 python 中 用作科学计算主要的 库\包) It is maintained by a large community (www.numpy.org). In this exercise you will learn several key numpy functions such as np.exp, np.log, and np.reshape.（主要的函数 指数 log 对数 还有矩阵的 reshape） You will need to know how to use these functions for future assignments.

#### 1.1 - sigmoid function, np.exp()

**Exercise:** Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.

**Reminder:** 
$ sigmoid(x)= \frac{1}{1+ e^ {-x }}$   is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

<img src="http://img.blog.csdn.net/20170921212049012?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvS29hbGFfVHJlZQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast">

In [3]:
# GRADED FUNCTION: basic_sigmoid

import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    #  math.exp(x) 相当于 e 的 x 次方   
    s = 1.0 / (1 + 1/ math.exp(x))
    ### END CODE HERE ###

    return s

In [4]:
basic_sigmoid(3)

0.9525741268224334

Actually, we rarely use the “math” library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful.

不常用 math 这个库，因为因为它的输入参数为实数，而实际上，在 deep learning 中，我们常用到的训练数据
都是 矩阵 或向量的形式,所以 numpy 这个库，非常的有用

In [5]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.参数类型错误

TypeError: must be real number, not list

In fact, if $ x=(x_1,x_2,...,x_n)$  is a row vector then $ np.exp(x)$ will apply the exponential(指数) function to every element of x.每个元素的指数 The output will thus be:$ np.exp(x)=(e^{x1},e^{x2},...,e^{xn})$

In [7]:
import numpy as np

# example of np.exp
a = np.array([1,2,3])

print(np.exp(a))# result is (exp(1), exp(2), exp(3))

[  2.71828183   7.3890561   20.08553692]


Furthermore 此外, if x is a vector, then a Python operation such as $s=x+3$ or $s=\frac{1}{x}$ will output $s$ as a vector of the same size as $x$. S 作为一个向量，其大小和 X 是一样的。

In [8]:
# example of vector operation
x = np.array([1,2,3])

print(x+3)

[4 5 6]


**Exercise**: Implement the sigmoid function using numpy. 使用 numpy 实现 sigmoid 函数

**Instructions**: x could now be either a real number, a vector, or a matrix.可以是 实数、向量、矩阵 The data structures we use in numpy to represent these shapes (vectors, matrices…) are called numpy arrays. You don’t need to know more for now. 

<img src="https://raw.githubusercontent.com/laobadao/Deep-Learning/master/homework/Jupyter/jupyter_note/pic/simoid2.png">

In [9]:
import numpy as np # this means you can access numpy functions by writing np.function() instead of numpy.function()

def sigmoid1(x):
	"""
	Compute the sigmoid of x

	Arguments:
	x -- A scalar (标量) or numpy array of any size.或任意大小的数组

	Return:
	s -- sigmoid1(x)
	"""

	### START CODE HERE ### (≈ 1 line of code)
	s = 1.0/(1+1/np.exp(x))
	### END CODE HERE ###

	return s

x = np.array([1,2,3])
print(sigmoid1(x))

[ 0.73105858  0.88079708  0.95257413]
